[user]
name = "Matt Keeter"
email = "matt.j.keeter@gmail.com"

[ui]
default-command = "log"
editor = "nvim"
diff-formatter = ":git"
diff-editor = ":builtin"

[aliases]
sq = ["squash"]
dup = ["duplicate"]
track = ["util", "exec", "--", "jj-track"]

[templates]
log = 'builtin_log_oneline'

# Adjust the global timestamp to not show seconds
[template-aliases]
'format_timestamp(timestamp)' = 'timestamp.local().format("%Y-%m-%d %H:%M")'
