#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH=~/code/kokopelli:$PATH
export PATH=~/code/gcc-arm-none-eabi-4_8-2013q4/bin:$PATH
export PATH=~/mit/cba/repos/kokompe/dev/mod/bin:$PATH
export PATH=~/Library/Python/2.7/bin:$PATH

alias vim="~/Applications/MacVim.app/Contents/MacOS/Vim"
rgrep() { grep -r $1 *; }

alias org="vim ~/org"

alias miniterm="python -m serial.tools.miniterm"

# Python: import installed packages before system packages
export PYTHONPATH=/Library/Python/2.7/site-packages:$PYTHONPATH

# Edit homebrew formulas in vim
export HOMEBREW_EDITOR=vim

# Run make with 8 threads by default
export MAKEFLAGS='-j8'

# Start fasd running
eval "$(fasd --init auto)"
